# -*- coding: mbcs -*-
#
# Abaqus/CAE Release 2016 replay file
# Internal Version: 2015_09_24-22.31.09 126547
# Run by fe1 on Mon Apr 23 08:36:38 2018
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=246.084625244141, 
    height=121.657890319824)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from caeModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
Mdb()
#: A new model database has been created.
#: The model "Model-1" has been created.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=200.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(-70.0, 10.0), point2=(31.25, 10.0))
s.HorizontalConstraint(entity=g[2], addUndoState=False)
s.Line(point1=(31.25, 10.0), point2=(31.25, 5.0))
s.VerticalConstraint(entity=g[3], addUndoState=False)
s.PerpendicularConstraint(entity1=g[2], entity2=g[3], addUndoState=False)
s.Line(point1=(31.25, 5.0), point2=(-70.0, 5.0))
s.HorizontalConstraint(entity=g[4], addUndoState=False)
s.PerpendicularConstraint(entity1=g[3], entity2=g[4], addUndoState=False)
s.Line(point1=(-70.0, 5.0), point2=(-70.0, 10.0))
s.VerticalConstraint(entity=g[5], addUndoState=False)
s.PerpendicularConstraint(entity1=g[4], entity2=g[5], addUndoState=False)
s.EqualLengthConstraint(entity1=g[2], entity2=g[4])
s.EqualLengthConstraint(entity1=g[5], entity2=g[3])
s.HorizontalDimension(vertex1=v[0], vertex2=v[1], textPoint=(30.3413772583008, 
    19.5119285583496), value=1600.0)
session.viewports['Viewport: 1'].view.setValues(nearPlane=553.067, 
    farPlane=590.271, width=158.972, height=58.3358, cameraPosition=(-63.8078, 
    11.7658, 571.669), cameraTarget=(-63.8078, 11.7658, 0))
s.ObliqueDimension(vertex1=v[0], vertex2=v[3], textPoint=(-77.5595932006836, 
    4.86927700042725), value=100.0)
session.viewports['Viewport: 1'].view.setValues(nearPlane=421.757, 
    farPlane=721.581, width=1334, height=489.518, cameraPosition=(254.648, 
    60.4695, 571.669), cameraTarget=(254.648, 60.4695, 0))
mdb.saveAs(
    pathName='/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3')
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
s.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__profile__']
s1 = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=2000.0)
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=STANDALONE)
s1.rectangle(point1=(-650.0, 150.0), point2=(550.0, 50.0))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[3], textPoint=(554.357727050781, 
    208.785278320312), value=1600.0)
s1.VerticalDimension(vertex1=v[3], vertex2=v[2], textPoint=(633.442932128906, 
    50.8677062988281), value=100.0)
s1.EqualLengthConstraint(entity1=g[5], entity2=g[3])
#: Warning: Select two or more lines.
session.viewports['Viewport: 1'].view.setValues(nearPlane=1465.24, 
    farPlane=2306, width=3592.62, height=1318.33, cameraPosition=(283.397, 
    231.542, 1885.62), cameraTarget=(283.397, 231.542, 0))
p = mdb.models['Model-1'].Part(name='plate', dimensionality=TWO_D_PLANAR, 
    type=DEFORMABLE_BODY)
p = mdb.models['Model-1'].parts['plate']
p.BaseShell(sketch=s1)
s1.unsetPrimaryObject()
p = mdb.models['Model-1'].parts['plate']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
del mdb.models['Model-1'].sketches['__profile__']
p = mdb.models['Model-1'].parts['plate']
s = p.features['Shell planar-1'].sketch
mdb.models['Model-1'].ConstrainedSketch(name='__edit__', objectToCopy=s)
s2 = mdb.models['Model-1'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
mdb.models['Model-1'].Material(name='Material-plate')
mdb.models['Model-1'].materials['Material-plate'].Plastic(table=((220.0, 0.0), 
    ))
mdb.models['Model-1'].materials['Material-plate'].Elastic(table=((70000.0, 
    0.3), ))
mdb.models['Model-1'].HomogeneousSolidSection(name='Section-plate', 
    material='Material-plate', thickness=1600.0)
p = mdb.models['Model-1'].parts['plate']
f = p.faces
faces = f.getSequenceFromMask(mask=('[#1 ]', ), )
region = p.Set(faces=faces, name='Set-1')
p = mdb.models['Model-1'].parts['plate']
p.SectionAssignment(region=region, sectionName='Section-plate', offset=0.0, 
    offsetType=MIDDLE_SURFACE, offsetField='', 
    thicknessAssignment=FROM_SECTION)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    optimizationTasks=OFF, geometricRestrictions=OFF, stopConditions=OFF)
a = mdb.models['Model-1'].rootAssembly
a.DatumCsysByDefault(CARTESIAN)
p = mdb.models['Model-1'].parts['plate']
a.Instance(name='plate-1', part=p, dependent=ON)
p1 = mdb.models['Model-1'].parts['plate']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', 
    sheetSize=2000.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.rectangle(point1=(-550.0, -200.0), point2=(-300.0, 200.0))
s.EqualLengthConstraint(entity1=g[5], entity2=g[3])
s.EqualLengthConstraint(entity1=g[2], entity2=g[4])
s.ObliqueDimension(vertex1=v[0], vertex2=v[3], textPoint=(-295.8095703125, 
    -269.522766113281), value=300.0)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
s.delete(objectList=(d[0], ))
s.HorizontalDimension(vertex1=v[1], vertex2=v[2], textPoint=(-307.9765625, 
    283.188720703125), value=300.0)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
p = mdb.models['Model-1'].Part(name='rigid_press', dimensionality=TWO_D_PLANAR, 
    type=ANALYTIC_RIGID_SURFACE)
p = mdb.models['Model-1'].parts['rigid_press']
p.AnalyticRigidSurf2DPlanar(sketch=s)
s.unsetPrimaryObject()
p = mdb.models['Model-1'].parts['rigid_press']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
del mdb.models['Model-1'].sketches['__profile__']
session.viewports['Viewport: 1'].view.setValues(nearPlane=866.665, 
    farPlane=1133.33, width=1143.58, height=419.643, viewOffsetX=29.2917, 
    viewOffsetY=22.5973)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['Model-1'].rootAssembly
p = mdb.models['Model-1'].parts['rigid_press']
a.Instance(name='rigid_press-1', part=p, dependent=ON)
a = mdb.models['Model-1'].rootAssembly
del a.features['rigid_press-1']
session.viewports['Viewport: 1'].view.setValues(nearPlane=3196.54, 
    farPlane=3400.43, width=871.785, height=319.906, viewOffsetX=461.05, 
    viewOffsetY=279.851)
a1 = mdb.models['Model-1'].rootAssembly
p = mdb.models['Model-1'].parts['rigid_press']
a1.Instance(name='rigid_press-1', part=p, dependent=ON)
a1 = mdb.models['Model-1'].rootAssembly
p = mdb.models['Model-1'].parts['rigid_press']
a1.Instance(name='rigid_press-2', part=p, dependent=ON)
a = mdb.models['Model-1'].rootAssembly
del a.features['rigid_press-2']
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
session.viewports['Viewport: 1'].view.setValues(nearPlane=2972.78, 
    farPlane=3624.19, width=2892.58, height=1061.45, viewOffsetX=175.855, 
    viewOffsetY=175.172)
a1 = mdb.models['Model-1'].rootAssembly
a1.translate(instanceList=('rigid_press-1', ), vector=(0.1, 0.0, 0.0))
#: The instance rigid_press-1 was translated by 100.E-03, 0., 0. with respect to the assembly coordinate system
a1 = mdb.models['Model-1'].rootAssembly
a1.translate(instanceList=('rigid_press-1', ), vector=(0.0, 100.0, 0.0))
#: The instance rigid_press-1 was translated by 0., 100., 0. with respect to the assembly coordinate system
session.viewports['Viewport: 1'].view.setValues(nearPlane=2941.84, 
    farPlane=3655.13, width=3166.73, height=1162.05, viewOffsetX=225.382, 
    viewOffsetY=195.925)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
a1 = mdb.models['Model-1'].rootAssembly
a1.translate(instanceList=('rigid_press-1', ), vector=(0.0, 300.0, 0.0))
#: The instance rigid_press-1 was translated by 0., 300., 0. with respect to the assembly coordinate system
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
session.viewports['Viewport: 1'].view.setValues(nearPlane=3038.21, 
    farPlane=3558.76, width=2227.95, height=817.558, viewOffsetX=89.9739, 
    viewOffsetY=216.62)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
a = mdb.models['Model-1'].rootAssembly
e1 = a.instances['plate-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#4 ]', ), )
region = a.Set(edges=edges1, name='Set-1')
mdb.models['Model-1'].YsymmBC(name='BC-1', createStepName='Initial', 
    region=region, localCsys=None)
session.viewports['Viewport: 1'].view.setValues(nearPlane=3060.62, 
    farPlane=3536.35, width=2113.57, height=775.588, viewOffsetX=75.4265, 
    viewOffsetY=134.661)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
session.viewports['Viewport: 1'].view.setValues(nearPlane=3006.58, 
    farPlane=3590.39, width=2592.95, height=951.496, viewOffsetX=208.149, 
    viewOffsetY=188.4)
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p1 = mdb.models['Model-1'].parts['plate']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['Model-1'].parts['plate']
s1 = p.features['Shell planar-1'].sketch
mdb.models['Model-1'].ConstrainedSketch(name='__edit__', objectToCopy=s1)
s2 = mdb.models['Model-1'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
d[1].setValues(value=50, )
session.viewports['Viewport: 1'].view.setValues(nearPlane=3238.02, 
    farPlane=3936.03, width=2982.63, height=1094.49, cameraPosition=(-25.5375, 
    261.213, 3587.02), cameraTarget=(-25.5375, 261.213, 0))
s2.delete(objectList=(d[1], ))
s2.ObliqueDimension(vertex1=v[3], vertex2=v[2], textPoint=(612.947631835938, 
    48.7253723144531), value=50.0)
session.viewports['Viewport: 1'].view.setValues(nearPlane=3372.12, 
    farPlane=3801.93, width=1836.64, height=673.966, cameraPosition=(-178.236, 
    178.317, 3587.02), cameraTarget=(-178.236, 178.317, 0))
s2.EqualLengthConstraint(entity1=g[2], entity2=g[4])
s2.delete(objectList=(d[2], ))
session.viewports['Viewport: 1'].view.setValues(nearPlane=3421.48, 
    farPlane=3752.57, width=1414.8, height=519.169, cameraPosition=(-380.71, 
    154.487, 3587.02), cameraTarget=(-380.71, 154.487, 0))
s2.VerticalDimension(vertex1=v[0], vertex2=v[1], textPoint=(-1081.52734375, 
    54.4775543212891), value=50.0)
session.viewports['Viewport: 1'].view.setValues(nearPlane=2.52073e+10, 
    farPlane=2.52075e+10, width=9149.44, height=3357.44, cameraPosition=(
    2318.71, 524.472, 2.52073e+10), cameraTarget=(2318.71, 524.472, 0))
s2.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
p = mdb.models['Model-1'].parts['plate']
s = p.features['Shell planar-1'].sketch
mdb.models['Model-1'].ConstrainedSketch(name='__edit__', objectToCopy=s)
s1 = mdb.models['Model-1'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
d[1].setValues(value=50, )
d[1].setValues(value=99, )
d[1].setValues(value=50, )
s1.PerpendicularConstraint(entity1=g[2], entity2=g[3])
s1.PerpendicularConstraint(entity1=g[3], entity2=g[2])
s1.PerpendicularConstraint(entity1=g[2], entity2=g[3])
s1.EqualLengthConstraint(entity1=g[2], entity2=g[4])
s1.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['Model-1'].parts['plate']
e = p.edges
pickedEdges = e.getSequenceFromMask(mask=('[#5 ]', ), )
p.seedEdgeByNumber(edges=pickedEdges, number=160, constraint=FINER)
p = mdb.models['Model-1'].parts['plate']
e = p.edges
pickedEdges = e.getSequenceFromMask(mask=('[#5 ]', ), )
p.seedEdgeByNumber(edges=pickedEdges, number=100, constraint=FINER)
p = mdb.models['Model-1'].parts['plate']
e = p.edges
pickedEdges = e.getSequenceFromMask(mask=('[#a ]', ), )
p.seedEdgeByNumber(edges=pickedEdges, number=16, constraint=FINER)
p = mdb.models['Model-1'].parts['plate']
e = p.edges
pickedEdges = e.getSequenceFromMask(mask=('[#a ]', ), )
p.seedEdgeByNumber(edges=pickedEdges, number=10, constraint=FINER)
p = mdb.models['Model-1'].parts['plate']
e = p.edges
pickedEdges = e.getSequenceFromMask(mask=('[#a ]', ), )
p.seedEdgeByNumber(edges=pickedEdges, number=8, constraint=FINER)
p = mdb.models['Model-1'].parts['plate']
p.generateMesh()
elemType1 = mesh.ElemType(elemCode=CPS4R, elemLibrary=STANDARD, 
    secondOrderAccuracy=OFF, hourglassControl=DEFAULT, 
    distortionControl=DEFAULT)
elemType2 = mesh.ElemType(elemCode=CPS3, elemLibrary=STANDARD)
p = mdb.models['Model-1'].parts['plate']
f = p.faces
faces = f.getSequenceFromMask(mask=('[#1 ]', ), )
pickedRegions =(faces, )
p.setElementType(regions=pickedRegions, elemTypes=(elemType1, elemType2))
mdb.save()
#: The model database has been saved to "/home/fe1/Desktop/FiniteElementsAnalysis/assignment3/assignment3.cae".
a = mdb.models['Model-1'].rootAssembly
a.regenerate()
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF, adaptiveMeshConstraints=ON)
mdb.models['Model-1'].StaticStep(name='Step-1', previous='Initial')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='Step-1')
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='Initial')
mdb.models['Model-1'].steps['Initial'].suppress()
#* The Initial step cannot be suppressed.
session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='Step-1')
mdb.models['Model-1'].steps['Step-1'].setValues(nlgeom=ON)
mdb.models['Model-1'].steps.changeKey(fromName='Step-1', toName='My_Step')
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p1 = mdb.models['Model-1'].parts['rigid_press']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
session.viewports['Viewport: 1'].view.setValues(nearPlane=844.109, 
    farPlane=1155.89, width=1515.3, height=556.048, viewOffsetX=101.649, 
    viewOffsetY=16.2005)
p = mdb.models['Model-1'].parts['rigid_press']
v1, e, d1, n = p.vertices, p.edges, p.datums, p.nodes
p.ReferencePoint(point=p.InterestingPoint(edge=e[0], rule=MIDDLE))
p = mdb.models['Model-1'].parts['rigid_press']
s = p.features['2D Analytic rigid shell-1'].sketch
mdb.models['Model-1'].ConstrainedSketch(name='__edit__', objectToCopy=s)
s2 = mdb.models['Model-1'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['2D Analytic rigid shell-1'], filter=COPLANAR_EDGES)
s2.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
a1 = mdb.models['Model-1'].rootAssembly
a1.regenerate()
a = mdb.models['Model-1'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=ON, 
    constraints=ON, connectors=ON, engineeringFeatures=ON, 
    adaptiveMeshConstraints=OFF)
a = mdb.models['Model-1'].rootAssembly
s1 = a.instances['rigid_press-1'].edges
side2Edges1 = s1.getSequenceFromMask(mask=('[#f ]', ), )
region5=a.Surface(side2Edges=side2Edges1, name='Surf-1')
a = mdb.models['Model-1'].rootAssembly
r1 = a.instances['rigid_press-1'].referencePoints
refPoints1=(r1[2], )
region1=regionToolset.Region(referencePoints=refPoints1)
mdb.models['Model-1'].RigidBody(name='press_part', refPointRegion=region1, 
    surfaceRegion=region5)
session.viewports['Viewport: 1'].view.setValues(nearPlane=2980.09, 
    farPlane=3616.87, width=2726.36, height=1000.45, viewOffsetX=184.657, 
    viewOffsetY=299.545)
mdb.models['Model-1'].ContactProperty('IntProp-1')
mdb.models['Model-1'].interactionProperties['IntProp-1'].NormalBehavior(
    pressureOverclosure=HARD, allowSeparation=ON, 
    constraintEnforcementMethod=DEFAULT)
mdb.models['Model-1'].interactionProperties['IntProp-1'].TangentialBehavior(
    formulation=FRICTIONLESS)
#: The interaction property "IntProp-1" has been created.
a = mdb.models['Model-1'].rootAssembly
s1 = a.instances['rigid_press-1'].edges
side2Edges1 = s1.getSequenceFromMask(mask=('[#f ]', ), )
region1=a.Surface(side2Edges=side2Edges1, name='m_Surf-2')
a = mdb.models['Model-1'].rootAssembly
s1 = a.instances['plate-1'].edges
side1Edges1 = s1.getSequenceFromMask(mask=('[#1 ]', ), )
region2=a.Surface(side1Edges=side1Edges1, name='s_Surf-2')
mdb.models['Model-1'].SurfaceToSurfaceContactStd(name='Int-1', 
    createStepName='My_Step', master=region1, slave=region2, sliding=FINITE, 
    thickness=ON, interactionProperty='IntProp-1', adjustMethod=NONE, 
    initialClearance=OMIT, datumAxis=None, clearanceRegion=None)
#: The interaction "Int-1" has been created.
